name: pyqt5.12.2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - PyQt5>=5.15.0
    - PyQt-Fluent-Widgets>=1.1.0
    - pyqtgraph>=0.13.0
    - numpy>=1.21.0
    - RsInstrument>=1.70.0
    - pyvisa>=1.13.0
